/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      "colors": {
          // New "Case File" UI/UX System Tokens
          "page": "#F0F2F5",
          "surface": "#FFFFFF",
          "ink-primary": "#14213D",
          "ink-secondary": "#4A5468",
          "border-default": "#D8DCE3",
          "brand-primary": "#0F5C74",
          "brand-primary-hover": "#0C4A5E",
          "brand-primary-active": "#093A4A",
          "accent-amber": "#D98E04",
          "accent-red": "#B23A2E",
          "accent-green": "#2F6F4E",
          "focus-ring": "rgba(30,127,184,0.4)",
          
          // Legacy & AdminDashboard tokens mapped for complete styling & high contrast
          "bgBase": "#F0F2F5",
          "bgElevated": "#FFFFFF",
          "textPrimary": "#14213D",
          "textSecondary": "#4A5468",
          "accentPrimary": "#0F5C74",
          "statusClosed": "#2F6F4E",
          "priorityHigh": "#B23A2E",

          // Mapping existing utility classes to the new system to guarantee visual contrast on hover
          "surface-container-high": "#E2E8F0",
          "on-tertiary-container": "#FFFFFF",
          "primary": "#0F5C74",
          "tertiary-fixed-dim": "#D98E04",
          "on-secondary-fixed-variant": "#FFFFFF",
          "on-surface": "#14213D",
          "on-error": "#FFFFFF",
          "secondary-fixed-dim": "#2F6F4E",
          "on-secondary": "#FFFFFF",
          "on-tertiary": "#FFFFFF",
          "surface-variant": "#E2E8F0",
          "inverse-on-surface": "#FFFFFF",
          "primary-fixed": "#D8DCE3",
          "on-secondary-container": "#FFFFFF",
          "on-background": "#14213D",
          "on-primary": "#FFFFFF",
          "tertiary": "#D98E04",
          "surface-tint": "#0F5C74",
          "error": "#B23A2E",
          "inverse-surface": "#14213D",
          "on-primary-container": "#FFFFFF",
          "surface-container": "#FFFFFF",
          "secondary": "#0F5C74",
          "inverse-primary": "#FFFFFF",
          "secondary-fixed": "#2F6F4E",
          "surface-container-lowest": "#FFFFFF",
          "on-tertiary-fixed-variant": "#4A5468",
          "surface-container-low": "#F8FAFC",
          "surface-dim": "#D8DCE3",
          "on-tertiary-fixed": "#4A5468",
          "outline-variant": "#D8DCE3",
          "primary-fixed-dim": "#0C4A5E",
          "tertiary-fixed": "#D98E04",
          "error-container": "#B23A2E",
          "surface-bright": "#FFFFFF",
          "secondary-container": "#2F6F4E",
          "background": "#F0F2F5",
          "on-surface-variant": "#4A5468",
          "on-primary-fixed": "#FFFFFF",
          "on-primary-fixed-variant": "#FFFFFF",
          "primary-container": "#0F5C74",
          "surface-container-highest": "#D8DCE3",
          "tertiary-container": "#D98E04",
          "on-secondary-fixed": "#FFFFFF",
          "on-error-container": "#FFFFFF",
          "outline": "#D8DCE3"
      },
      "borderRadius": {
          "DEFAULT": "8px",
          "sm": "4px",
          "md": "8px",
          "lg": "10px",
          "xl": "16px",
          "2xl": "24px",
          "full": "9999px"
      },
      "spacing": {
          "container-max-width": "1280px",
          "gutter": "24px",
          "stack-lg": "32px",
          "margin-desktop": "32px",
          "margin-mobile": "16px",
          "unit": "4px",
          "stack-sm": "8px",
          "stack-md": "16px"
      },
      "fontFamily": {
          "body-md": ["'IBM Plex Sans'", "sans-serif"],
          "body-sm": ["'IBM Plex Sans'", "sans-serif"],
          "label-sm": ["'IBM Plex Sans'", "sans-serif"],
          "headline-lg-mobile": ["'Public Sans'", "sans-serif"],
          "display-lg": ["'Public Sans'", "sans-serif"],
          "headline-md": ["'Public Sans'", "sans-serif"],
          "headline-lg": ["'Public Sans'", "sans-serif"],
          "label-md": ["'IBM Plex Sans'", "sans-serif"],
          "body-lg": ["'IBM Plex Sans'", "sans-serif"],
          "sans": ["'IBM Plex Sans'", "sans-serif"],
          "mono": ["'IBM Plex Mono'", "monospace"]
      },
      "fontSize": {
          "body-md": ["15px", { "lineHeight": "1.30", "letterSpacing": "0", "fontWeight": "400" }],
          "body-sm": ["14px", { "lineHeight": "1.40", "letterSpacing": "0", "fontWeight": "400" }],
          "label-sm": ["13px", { "lineHeight": "1.20", "letterSpacing": "0", "fontWeight": "500" }],
          "headline-lg-mobile": ["24px", { "lineHeight": "1.30", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "display-lg": ["62px", { "lineHeight": "1.00", "letterSpacing": "-0.01em", "fontWeight": "700" }],
          "headline-md": ["22px", { "lineHeight": "1.20", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "headline-lg": ["32px", { "lineHeight": "1.13", "letterSpacing": "-0.01em", "fontWeight": "600" }],
          "label-md": ["14px", { "lineHeight": "1.00", "letterSpacing": "0", "fontWeight": "500" }],
          "body-lg": ["18px", { "lineHeight": "1.30", "letterSpacing": "0", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
